version: '3.8'

services:
  book-keeping-front:
    image: book-keeping-front:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-keeping-front-container
    ports:
      - "8001:80"
      - "443:443"
    restart: always
    networks:
      - bookeeper

networks:
  bookeeper:
    external: true

